<?php

/**
 * Implements template_preprocess_html().
 */
function subcellular_preprocess_html(&$vars) {
  /*
    // Set stylesheets
    $styles = array(
    'mystyle' => array(
    'file' => 'myStyle.css',
    'weight' => 10,
    ),
    'moarstyle' => array(
    'file' => 'moar.css',
    'weight' => 9,
    ),
    );
    // Set scripts.
    $scripts = array(
    'script' => array(
    'cdn' => '//mycdnlink.com/myJavascript.js',
    'file' => 'myJavascript.js',
    'object' => 'myTestObject',
    ),
    'plugins' => array(
    'file' => 'myOtherScript.js',
    'group' => JS_THEME,
    'weight' => 99,
    ),
    );

    // Add styles to page.
    cellular_add_css($styles);
    // Add scripts to page.
    cellular_attach_js($scripts);

    // Pass a variable to js as Drupal.settings.myVar:
    // drupal_add_js(array('myVar' => array('key' => 'value')), 'setting');

    //dpm($vars);

   */
}
