<?php
function subcellular_css_alter(&$css) {
/*
    // Remove stylesheets
    $exclude = array(
        // 'module' => path/to/style.css
        'calendar' => 'css/calendar_multiday.css',
        'ctools' => 'css/ctools.css',
        'views' => 'css/views.css',
        'logintoboggan' => 'logintoboggan.css',
        'panels' => array(
            'css/panels.css', 
            'plugins/layouts/flexible/flexible.css'
        ),
    );

    cellular_remove_css($exclude, $css);
  */  

   /*
    // Add stylesheets
    $add_css = array(
        'styleName' =>  array(
            'file' => cellular_theme_path() . '/css/stylesheet.css',

            'weight' => 1,
        ),
    );

    cellular_add_css($add_css, $css);
    */
}